version: '3.8'
services:
    database:
        image: 'mongo'
        container_name: 'mongo'
        volumes:
            - ../data/mongo:/data/db
        ports:
            - 27017-27019:27017-27019
    endpoint:
        depends_on:
            - database
        image: edgar
        environment:
            - address=mongodb://mongo
        build:
            context: edgar-analyzer
        ports:
            - 8889:8889
        volumes:
            - ./data:/workdir/data
        entrypoint: ["/bin/bash", "-c", "java -jar webapp.jar -Ddb.address=$address -Dspring.profiles.active=production"]
    crawler:
        depends_on:
            - database
        image: edgar
        environment:
            - address=mongodb://mongo
        build:
            context: edgar-analyzer
        volumes:
            - ./data:/workdir/data
        entrypoint: ["/bin/bash", "-c", "java -jar crawler.jar -Ddb.address=$address -Dspring.profiles.active=production"]
    app:
        depends_on:
            - endpoint
        image: viewer
        build:
            context: sec-report-viewer
        tty: true
        ports:
            - 80:3000
